apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mnemonicai
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
images:
  - name: ghcr.io/YOUR_GITHUB_ORG/mnemonicai
    newTag: latest
