apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mnemonicai-data
  namespace: mnemonicai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mnemonicai-models
  namespace: mnemonicai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
